# Generated by Django 3.2.9 on 2021-11-27 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='ClimateDataActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Tempreture')),
                ('year', models.CharField(max_length=50, verbose_name='Year')),
                ('statistics', models.CharField(max_length=150, verbose_name='statistics')),
                ('iso3', models.CharField(max_length=150, verbose_name='ISO3')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_data_actuals', to='analysis.country')),
            ],
        ),
        migrations.CreateModel(
            name='ClimateChangePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_temperature', models.FloatField(verbose_name='Montly tempreture')),
                ('year', models.CharField(max_length=50, verbose_name='Year')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('statistics', models.CharField(max_length=150, verbose_name='statistics')),
                ('iso3', models.CharField(max_length=150, verbose_name='ISO3')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_change_predictions', to='analysis.country')),
            ],
        ),
    ]
